# hosts.yml
---
all:
  children:
    rhel:
      children:
        ubi:
          children:
            ubi8:
              hosts:
                # none
              vars:
                securedevcontainer_variant: "ubi8"
            ubi9:
              hosts:
                localhost:
                  ansible_connection: local
              vars:
                securedevcontainer_variant: "ubi9"
...