# Ansible Playbook
# grype-feature/activate-feature.yml
---
- name: Activate DevContainer Feature - Grype
  hosts: ubi
  become: true
  gather_facts: false

  roles:
  - role: ansible-role-feature
    vars:
    - _securedevcontainer_variant: "{{ securedevcontainer_variant }}"
    - _grype_version: "{{ grype_version }}"
    - _grype_checksum: "{{ grype_checksum }}"
    - _target_username: "{{ remote_user }}"
    - _target_user_home: "{{ remote_user_home }}"
...
