# hosts.yml - Ansible inventory for devcontainer feature
---
all:
  children:
    rhel:
      children:
        ubi:
          children:
            ubi9:
              hosts:
                localhost:
                  ansible_connection: local
              vars:
                securedevcontainer_variant: "ubi9"
            ubi10:
              hosts:
                # none
              vars:
                securedevcontainer_variant: "ubi10"
...
