BASE_IMAGE_TAG ?= devcontainer-features-test-base:ubi9

.PHONY: help build-test-base test test-feature test-scenarios test-integration test-all docs-dev

.DEFAULT_GOAL := help

help:                                   ## Show this help message
	@grep -E '^[a-zA-Z_-]+:.*##' $(MAKEFILE_LIST) | awk -F ':.*## ' '{printf "  \033[36m%-20s\033[0m %s\n", $$1, $$2}'

build-test-base:                        ## Build the UBI9 base test image
	docker build -t $(BASE_IMAGE_TAG) -f .devcontainer/Containerfile .devcontainer/

test-feature: build-test-base           ## make test-feature FEATURE=bun
	bunx @devcontainers/cli features test -p . -f $(FEATURE) \
		-i $(BASE_IMAGE_TAG) -u vscode --skip-scenarios

test-scenarios:                         ## make test-scenarios FEATURE=claude-code
ifdef FEATURE
	bunx @devcontainers/cli features test -p . -f $(FEATURE) --skip-autogenerated
else
	bunx @devcontainers/cli features test -p . --skip-autogenerated
endif

test-integration:                       ## Global integration scenario
	bunx @devcontainers/cli features test -p . --global-scenarios-only

docs-dev:                               ## Run docs site locally in dev mode
	cd docs && bun --bun run dev

test: build-test-base                   ## Run ALL tests (autogenerated + scenarios + global)
	bunx @devcontainers/cli features test -p . \
		-i $(BASE_IMAGE_TAG) -u vscode --skip-scenarios
	bunx @devcontainers/cli features test -p . --skip-autogenerated
	bunx @devcontainers/cli features test -p . --global-scenarios-only
