BASE_IMAGE_TAG ?= devcontainer-features-test-base:ubi9

.PHONY: build-test-base test test-feature test-scenarios test-integration test-all

build-test-base:
	docker build -t $(BASE_IMAGE_TAG) -f .devcontainer/Containerfile .devcontainer/

test-feature: build-test-base           ## make test-feature FEATURE=bun
	bunx @devcontainers/cli features test -p . -f $(FEATURE) \
		-i $(BASE_IMAGE_TAG) -u vscode --skip-scenarios

test-scenarios:                         ## make test-scenarios FEATURE=claude-code
ifdef FEATURE
	bunx @devcontainers/cli features test -p . -f $(FEATURE) --skip-autogenerated
else
	bunx @devcontainers/cli features test -p . --skip-autogenerated
endif

test-integration:                       ## Global integration scenario
	bunx @devcontainers/cli features test -p . --global-scenarios-only

test: build-test-base                   ## Run ALL tests (autogenerated + scenarios + global)
	bunx @devcontainers/cli features test -p . \
		-i $(BASE_IMAGE_TAG) -u vscode --skip-scenarios
	bunx @devcontainers/cli features test -p . --skip-autogenerated
	bunx @devcontainers/cli features test -p . --global-scenarios-only
