BASE_IMAGE_TAG ?= devcontainer-features-test-base:fedora43

.PHONY: help build-test-base test test-feature test-scenarios test-integration docs-dev \
        check-contract test-contract test-template test-templates

.DEFAULT_GOAL := help

help:                                   ## Show this help message
	@grep -E '^[a-zA-Z_-]+:.*##' $(MAKEFILE_LIST) | awk -F ':.*## ' '{printf "  \033[36m%-20s\033[0m %s\n", $$1, $$2}'

build-test-base:                        ## Build the UBI9 base test image
	docker build -t $(BASE_IMAGE_TAG) -f .devcontainer/Containerfile .devcontainer/

test-feature: build-test-base           ## make test-feature FEATURE=bun
	bunx @devcontainers/cli features test -p . -f $(FEATURE) \
		-i $(BASE_IMAGE_TAG) -u dev --skip-scenarios

test-scenarios:                         ## make test-scenarios FEATURE=claude-code
ifdef FEATURE
	bunx @devcontainers/cli features test -p . -f $(FEATURE) --skip-autogenerated
else
	bunx @devcontainers/cli features test -p . --skip-autogenerated
endif

test-integration:                       ## Global integration scenario
	bunx @devcontainers/cli features test -p . --global-scenarios-only

TEMPLATES := go-cue dotnet-node java python ansible-cue extras

check-contract:                         ## Verify every role satisfies the ADR-012 parameter contract
	@bash scripts/check-role-contract.sh

# Mirrors the CI "Prepare test template" step: features are referenced as
# "./<id>" relative to .devcontainer/, so they must be copied in first.
test-template:                          ## Build one template and run its tests (TEMPLATE=python)
	@test -n "$(TEMPLATE)" || { echo "usage: make test-template TEMPLATE=<name>"; exit 1; }
	@for d in test-templates/$(TEMPLATE)/.devcontainer/*/; do [ -d "$$d" ] && rm -rf "$$d"; done; true
	@rm -f test-templates/$(TEMPLATE)/.devcontainer/devcontainer-lock.json
	@# devcontainer up reuses a container with a matching id-label, which would
	@# silently skip the rebuild and test stale features.
	@docker ps -aq --filter "label=test=$(TEMPLATE)" | xargs -r docker rm -f >/dev/null 2>&1; true
	cp -r src/* test-templates/$(TEMPLATE)/.devcontainer/
	cp test-templates/shared/test-lib.sh test-templates/$(TEMPLATE)/
	npx --yes @devcontainers/cli up --workspace-folder "$(CURDIR)/test-templates/$(TEMPLATE)" \
		--id-label "test=$(TEMPLATE)"
	npx --yes @devcontainers/cli exec --workspace-folder "$(CURDIR)/test-templates/$(TEMPLATE)" \
		--id-label "test=$(TEMPLATE)" bash tests.sh

# Idempotency and failure-mode tests. Runs on the host via `docker exec -u 0`,
# because run-feature.sh needs root and `devcontainer exec` only ever gets `dev`.
test-contract:                          ## Run contract tests against a running template (TEMPLATE=python)
	@test -n "$(TEMPLATE)" || { echo "usage: make test-contract TEMPLATE=<name>"; exit 1; }
	bash test-templates/shared/contract-tests.sh $(TEMPLATE)

test-templates:                         ## Build, test and contract-test every template
	@for t in $(TEMPLATES); do \
		echo "===== $$t ====="; \
		$(MAKE) --no-print-directory test-template TEMPLATE=$$t || exit 1; \
		$(MAKE) --no-print-directory test-contract  TEMPLATE=$$t || exit 1; \
	done

docs-dev:                               ## Run docs site locally in dev mode
	cd docs && bun --bun run dev

test: build-test-base                   ## Run ALL tests (autogenerated + scenarios + global)
	bunx @devcontainers/cli features test -p . \
		-i $(BASE_IMAGE_TAG) -u dev --skip-scenarios
	bunx @devcontainers/cli features test -p . --skip-autogenerated
	bunx @devcontainers/cli features test -p . --global-scenarios-only
