# Ansible Playbook
# dotnet-feature/activate-feature.yml
---
- name: Activate DevContainer Feature - .NET SDK
  hosts: ubi
  become: false
  gather_facts: false

  roles:
  - role: ansible-role-feature
    vars:
      _securedevcontainer_variant: "{{ securedevcontainer_variant }}"
      _dotnet_version: "{{ dotnet_version }}"
      _dotnet_checksum: "{{ dotnet_checksum }}"
      _target_username: "{{ remote_user }}"
      _target_user_home: "{{ remote_user_home }}"
...
