# Ansible Playbook
# ansible-core-feature/activate-feature.yml
---
- name: Activate DevContainer Feature - ansible-core
  hosts: ubi
  become: true
  gather_facts: false

  roles:
  - role: ansible-role-feature
    vars:
    - _securedevcontainer_variant: "{{ securedevcontainer_variant }}"
    - _ansible_core_version: "{{ ansible_core_version }}"
    - _target_python_version: "{{ target_python_version }}"
    - _target_username: "{{ remote_user }}"
    - _target_user_home: "{{ remote_user_home }}"
...