FROM registry.access.redhat.com/ubi9/ubi:latest

# ##########################################################################################
# BEGIN: Bootstrap common configuration
# ##########################################################################################
USER root

# Silence subscription messages
RUN echo "enabled=0" >> /etc/yum/pluginconf.d/subscription-manager.conf \
 && dnf update --disablerepo=* --enablerepo=ubi-9-appstream-rpms --enablerepo=ubi-9-baseos-rpms -y && rm -rf /var/cache/yum
 
# Install required OS packages
RUN dnf install -y --disablerepo=* --enablerepo=ubi-9-appstream-rpms --enablerepo=ubi-9-baseos-rpms \
        # Required for Ansible-based Feature activation
        sudo \
        python3-pip \
 && rm -rf /var/cache/yum

# Create the DevContainer user; default to 'vscode 1000:1000'
ENV SECUREDEVCONTAINER_USERNAME=${SECUREDEVCONTAINER_USERNAME:-vscode}
ENV SECUREDEVCONTAINER_USER_UID=${SECUREDEVCONTAINER_USER_UID:-1000}
ENV SECUREDEVCONTAINER_USER_GID=${SECUREDEVCONTAINER_USER_GID:-$SECUREDEVCONTAINER_USER_UID}

RUN groupadd --gid $SECUREDEVCONTAINER_USER_GID $SECUREDEVCONTAINER_USERNAME \
    && useradd -m -s /bin/bash --uid $SECUREDEVCONTAINER_USER_UID --gid $SECUREDEVCONTAINER_USER_GID $SECUREDEVCONTAINER_USERNAME
    # Add sudo support. Omit if you don't need to install software after connecting.
    # && echo $SECUREDEVCONTAINER_USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$SECUREDEVCONTAINER_USERNAME \
    # && chmod 0440 /etc/sudoers.d/$SECUREDEVCONTAINER_USERNAME

USER $SECUREDEVCONTAINER_USERNAME

ENV SECUREDEVCONTAINER_USER_HOME=${SECUREDEVCONTAINER_USER_HOME:-/home/$SECUREDEVCONTAINER_USERNAME}
# devcontainer user local executable path
# example: /home/vscode/.local/bin
ENV SECUREDEVCONTAINER_USER_LOCAL_BIN_PATH=${SECUREDEVCONTAINER_USER_HOME}/.local/bin

RUN export PATH="${SECUREDEVCONTAINER_USER_LOCAL_BIN_PATH}:$PATH" \
 && echo 'export PATH="${SECUREDEVCONTAINER_USER_LOCAL_BIN_PATH}:$PATH"' | tee -a ${SECUREDEVCONTAINER_USER_HOME}/.bashrc > /dev/null \
 && echo 'export PATH="${SECUREDEVCONTAINER_USER_LOCAL_BIN_PATH}:$PATH"' | tee -a ${SECUREDEVCONTAINER_USER_HOME}/.bash_profile > /dev/null

USER root

# Create 'ansible' user for feature installations. 'ansible' is the default feature bootstrap user. 
# 'ansible' MUST be part of the 'wheel' group because Ansible-managed feature activation often requires 'root' access.
ENV SECUREDEVCONTAINER_FEATURE_USERNAME=${SECUREDEVCONTAINER_FEATURE_USERNAME:-ansible}
ENV SECUREDEVCONTAINER_FEATURE_USER_UID=${SECUREDEVCONTAINER_FEATURE_USER_UID:-1001}
ENV SECUREDEVCONTAINER_FEATURE_USER_GID=${SECUREDEVCONTAINER_FEATURE_USER_GID:-$SECUREDEVCONTAINER_FEATURE_USER_UID}

RUN groupadd --gid $SECUREDEVCONTAINER_FEATURE_USER_GID $SECUREDEVCONTAINER_FEATURE_USERNAME \
 && useradd -m -s /bin/bash --uid $SECUREDEVCONTAINER_FEATURE_USER_UID --gid $SECUREDEVCONTAINER_FEATURE_USER_GID $SECUREDEVCONTAINER_FEATURE_USERNAME \
 # Add sudo access sans password 
 && usermod -aG wheel $SECUREDEVCONTAINER_FEATURE_USERNAME \
 && echo "${SECUREDEVCONTAINER_FEATURE_USERNAME}    ALL=(ALL)    NOPASSWD: ALL" > /etc/sudoers.d/$SECUREDEVCONTAINER_FEATURE_USERNAME \
 && chmod 0440 /etc/sudoers.d/$SECUREDEVCONTAINER_FEATURE_USERNAME \
 && cat /etc/sudoers.d/$SECUREDEVCONTAINER_FEATURE_USERNAME

USER $SECUREDEVCONTAINER_FEATURE_USERNAME

ENV SECUREDEVCONTAINER_FEATURE_USER_HOME=${SECUREDEVCONTAINER_FEATURE_USER_HOME:-/home/$SECUREDEVCONTAINER_FEATURE_USERNAME}
# Ansible executable path
# /home/ansible/.local/bin
ENV SECUREDEVCONTAINER_FEATURE_USER_LOCAL_BIN_PATH=${SECUREDEVCONTAINER_FEATURE_USER_HOME}/.local/bin

# Copy Ansible Inventory file to the feature bootstrap user's home path
COPY ./devcontainer-resources/hosts.yml $SECUREDEVCONTAINER_FEATURE_USER_HOME/hosts.yml

# Install Ansible to faciliate DevContainer Feature activation
ENV SECUREDEVCONTAINER_FEATURE_BOOTSTRAP_ANSIBLE_CORE_VERSION=${SECUREDEVCONTAINER_FEATURE_BOOTSTRAP_ANSIBLE_CORE_VERSION:-2.14.5}

RUN pip3 install --user ansible-core=="${SECUREDEVCONTAINER_FEATURE_BOOTSTRAP_ANSIBLE_CORE_VERSION}" \
 && export PATH="${SECUREDEVCONTAINER_FEATURE_USER_LOCAL_BIN_PATH}:$PATH" \ 
 && echo 'export PATH="${SECUREDEVCONTAINER_FEATURE_USER_LOCAL_BIN_PATH}:$PATH"' | tee -a ${SECUREDEVCONTAINER_FEATURE_USER_HOME}/.bashrc > /dev/null \
 && echo 'export PATH="${SECUREDEVCONTAINER_FEATURE_USER_LOCAL_BIN_PATH}:$PATH"' | tee -a ${SECUREDEVCONTAINER_FEATURE_USER_HOME}/.bash_profile > /dev/null \
 && ansible --version

USER $SECUREDEVCONTAINER_USERNAME

ENTRYPOINT ["$@"]
CMD ["sleep", "infinity"]
# ##########################################################################################
# END: Bootstrap common configuration
# ##########################################################################################


