# Ansible Playbook
# bun-feature/activate-feature.yml
---
- name: Activate DevContainer Feature - Bun
  hosts: ubi
  become: true
  gather_facts: false

  roles:
  - role: ansible-role-feature
    vars:
    - _securedevcontainer_variant: "{{ securedevcontainer_variant }}"
    - _bun_version: "{{ bun_version }}"
    - _bun_checksum: "{{ bun_checksum }}"
    - _target_username: "{{ remote_user }}"
    - _target_user_home: "{{ remote_user_home }}"
...
