# Ansible Playbook
# uv-ruff-feature/activate-feature.yml
---
- name: Activate DevContainer Feature - UV + Ruff
  hosts: ubi
  become: false
  gather_facts: false

  roles:
  - role: ansible-role-feature
    vars:
      _securedevcontainer_variant: "{{ securedevcontainer_variant }}"
      _uv_version: "{{ uv_version }}"
      _uv_checksum: "{{ uv_checksum }}"
      _ruff_version: "{{ ruff_version }}"
      _target_username: "{{ remote_user }}"
      _target_user_home: "{{ remote_user_home }}"
...
