# golang-feature/ansible-role-feature/tasks/main.yml
---
# Assert that the devcontainer variant is compatible with this role
- name: Assert that _securedevcontainer_variant is in the _securedevcontainer_compatibility_list
  ansible.builtin.assert:
    that: _securedevcontainer_variant in _securedevcontainer_compatibility_list
    fail_msg: "_securedevcontainer_variant = '{{ _securedevcontainer_variant }}' is NOT in the _securedevcontainer_compatibility_list = '{{ _securedevcontainer_compatibility_list }}'."
    success_msg: "_securedevcontainer_variant = '{{ _securedevcontainer_variant }}' is in the _securedevcontainer_compatibility_list = '{{ _securedevcontainer_compatibility_list }}'."

- name: Extract the UBI version number from _securedevcontainer_variant
  ansible.builtin.set_fact:
    _securedevcontainer_ubi_version: "{{ _securedevcontainer_variant | regex_replace('^.*?(\\d+)$', '\\1') }}"

- name: Display _securedevcontainer_ubi_version
  ansible.builtin.debug:
    msg: "UBI version number: {{ _securedevcontainer_ubi_version }}"

# Golang installation tasks
- name: Check if Golang is already installed
  ansible.builtin.command: "{{ _target_user_home }}/.local/share/go/bin/go version"
  ignore_errors: true
  register: _go_version_result
  changed_when: false

- name: Remove current Golang installation
  ansible.builtin.file:
    state: absent
    path: "{{ _target_user_home }}/.local/share/go"
  when:
    - _go_version_result is succeeded
    - _go_version not in _go_version_result.stdout

- name: Create temporary download directory
  ansible.builtin.file:
    path: /tmp/golang-feature-install
    state: directory
    mode: '0755'
  when: _go_version_result is failed
        or _go_version not in _go_version_result.stdout

- name: Download Golang binary
  ansible.builtin.get_url:
    url: "{{ _go_download_url }}"
    dest: "/tmp/golang-feature-install/{{ _go_tarball }}"
    checksum: "sha256:{{ _go_checksum }}"
  when: _go_version_result is failed
        or _go_version not in _go_version_result.stdout

- name: Ensure ~/.local/share directory exists
  ansible.builtin.file:
    path: "{{ _target_user_home }}/.local/share"
    state: directory
    mode: '0755'
    owner: "{{ _target_username }}"
    group: "{{ _target_username }}"

- name: Extract Golang binary
  ansible.builtin.unarchive:
    src: "/tmp/golang-feature-install/{{ _go_tarball }}"
    dest: "{{ _target_user_home }}/.local/share"
    copy: no
  when: _go_version_result is failed
        or _go_version not in _go_version_result.stdout

- name: Ensure ~/.local/share/gopath directory exists
  ansible.builtin.file:
    path: "{{ _target_user_home }}/.local/share/gopath"
    state: directory
    mode: '0755'
    owner: "{{ _target_username }}"
    group: "{{ _target_username }}"

- name: Recursively change ownership of Go installation
  ansible.builtin.file:
    path: "{{ _target_user_home }}/.local/share/go"
    owner: "{{ _target_username }}"
    group: "{{ _target_username }}"
    recurse: true

- name: Remove temporary download directory
  ansible.builtin.file:
    path: /tmp/golang-feature-install
    state: absent

- name: Get Golang version
  ansible.builtin.command:
    cmd: "{{ _target_user_home }}/.local/share/go/bin/go version"
  register: _go_version_result

- name: Assert that Golang is installed and accessible
  ansible.builtin.assert:
    that: "'go version' in _go_version_result.stdout"
    fail_msg: "{{ _go_version_result.stdout }}"
    success_msg: "{{ _go_version_result.stdout }}"

# Cleanup
- name: Unset _securedevcontainer_ubi_version
  ansible.builtin.set_fact:
    _securedevcontainer_ubi_version: null
...