# grype-feature/ansible-role-feature/tasks/main.yml
---
# Assert that the devcontainer variant is compatible with this role
- name: Assert that _securedevcontainer_variant is in the _securedevcontainer_compatibility_list
  ansible.builtin.assert:
    that: _securedevcontainer_variant in _securedevcontainer_compatibility_list
    fail_msg: "_securedevcontainer_variant = '{{ _securedevcontainer_variant }}' is NOT in the _securedevcontainer_compatibility_list = '{{ _securedevcontainer_compatibility_list }}'."
    success_msg: "_securedevcontainer_variant = '{{ _securedevcontainer_variant }}' is in the _securedevcontainer_compatibility_list = '{{ _securedevcontainer_compatibility_list }}'."

- name: Extract the UBI version number from _securedevcontainer_variant
  ansible.builtin.set_fact:
    _securedevcontainer_ubi_version: "{{ _securedevcontainer_variant | regex_replace('^.*?(\\d+)$', '\\1') }}"

- name: Display _securedevcontainer_ubi_version
  ansible.builtin.debug:
    msg: "UBI version number: {{ _securedevcontainer_ubi_version }}"

# Grype installation tasks
- name: Check if Grype is already installed
  ansible.builtin.command: "{{ _target_user_home }}/.local/bin/grype version"
  ignore_errors: true
  register: _grype_version_result
  changed_when: false

- name: Create temporary download directory
  ansible.builtin.file:
    path: /tmp/grype-feature-install
    state: directory
    mode: '0755'
  when: _grype_version_result is failed
        or _grype_version not in _grype_version_result.stdout

- name: Download Grype checksums file
  ansible.builtin.get_url:
    url: "{{ _grype_checksums_download_url }}"
    dest: "/tmp/grype-feature-install/{{ _grype_checksums_file }}"
  when:
    - _grype_version_result is failed or _grype_version not in _grype_version_result.stdout
    - _grype_checksum | default('', true) | length == 0

- name: Read checksums file
  ansible.builtin.slurp:
    src: "/tmp/grype-feature-install/{{ _grype_checksums_file }}"
  register: _grype_checksums_file_content
  when: _grype_checksum | default('', true) | length == 0

- name: Find the checksum for {{ _grype_tarball }}
  ansible.builtin.set_fact:
    _grype_checksum: "{{ item.split()[0] }}"
  when:
    - _grype_checksum | default('', true) | length == 0
    - _grype_tarball in item
  loop: "{{ _grype_checksums_file_content.content | b64decode | split('\n') | reject('eq', '') | list }}"

- name: Display the checksum
  ansible.builtin.debug:
    msg: "Checksum for {{ _grype_tarball }} is: {{ _grype_checksum }}"

- name: Download Grype binary
  ansible.builtin.get_url:
    url: "{{ _grype_download_url }}"
    dest: "/tmp/grype-feature-install/{{ _grype_tarball }}"
    checksum: "sha256:{{ _grype_checksum }}"
  when: _grype_version_result is failed
        or _grype_version not in _grype_version_result.stdout

- name: Ensure ~/.local/bin directory exists
  ansible.builtin.file:
    path: "{{ _target_user_home }}/.local/bin"
    state: directory
    mode: '0755'
    owner: "{{ _target_username }}"
    group: "{{ _target_username }}"

- name: Extract Grype binary to ~/.local/bin
  ansible.builtin.unarchive:
    src: "/tmp/grype-feature-install/{{ _grype_tarball }}"
    dest: "{{ _target_user_home }}/.local/bin"
    copy: no
    extra_opts:
      - --wildcards
      - grype
  when: _grype_version_result is failed
        or _grype_version not in _grype_version_result.stdout

- name: Set ownership of grype binary
  ansible.builtin.file:
    path: "{{ _target_user_home }}/.local/bin/grype"
    owner: "{{ _target_username }}"
    group: "{{ _target_username }}"
    mode: '0755'

- name: Remove temporary download directory
  ansible.builtin.file:
    path: /tmp/grype-feature-install
    state: absent

- name: Get Grype version
  ansible.builtin.command:
    cmd: "{{ _target_user_home }}/.local/bin/grype version"
  register: _grype_version_result

- name: Assert that Grype is installed and accessible
  ansible.builtin.assert:
    that: "'Application' in _grype_version_result.stdout or 'grype' in _grype_version_result.stdout"
    fail_msg: "{{ _grype_version_result.stdout }}"
    success_msg: "{{ _grype_version_result.stdout }}"

# Cleanup
- name: Unset _securedevcontainer_ubi_version
  ansible.builtin.set_fact:
    _securedevcontainer_ubi_version: null
...
